// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTa_mLR4Az7hVWvNkToVdZEvJ-d9Cy9_s',
    appId: '1:325642642626:web:d5fe659e9e2e07cb90875b',
    messagingSenderId: '325642642626',
    projectId: 'react-proyect-jv',
    authDomain: 'react-proyect-jv.firebaseapp.com',
    storageBucket: 'react-proyect-jv.firebasestorage.app',
    measurementId: 'G-MPDSRLV3YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsCYXc2MVeVIctj6w-hJ4DELO3d6eRI8o',
    appId: '1:325642642626:android:9eb1f68eda697eb890875b',
    messagingSenderId: '325642642626',
    projectId: 'react-proyect-jv',
    storageBucket: 'react-proyect-jv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0v256y1mBA02llCBfu1ZZSAhqquiRecA',
    appId: '1:325642642626:ios:48b91a6388d4199f90875b',
    messagingSenderId: '325642642626',
    projectId: 'react-proyect-jv',
    storageBucket: 'react-proyect-jv.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0v256y1mBA02llCBfu1ZZSAhqquiRecA',
    appId: '1:325642642626:ios:48b91a6388d4199f90875b',
    messagingSenderId: '325642642626',
    projectId: 'react-proyect-jv',
    storageBucket: 'react-proyect-jv.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );
}
